export const ADMIN_LIST_USERS_REQUEST = 'ADMIN_LIST_USERS_REQUEST';
export const ADMIN_LIST_USERS_SUCCESS = 'ADMIN_LIST_USERS_SUCCESS';
export const ADMIN_LIST_USERS_FAILURE = 'ADMIN_LIST_USERS_FAILURE';

export const ADMIN_DELETE_USER_REQUEST = 'ADMIN_DELETE_USER_REQUEST';
export const ADMIN_DELETE_USER_SUCCESS = 'ADMIN_DELETE_USER_SUCCESS';
export const ADMIN_DELETE_USER_FAILURE = 'ADMIN_DELETE_USER_FAILURE';

export const ADMIN_APPROVE_APPLICATION_REQUEST = 'ADMIN_APPROVE_APPLICATION_REQUEST';
export const ADMIN_APPROVE_APPLICATION_SUCCESS = 'ADMIN_APPROVE_APPLICATION_SUCCESS';
export const ADMIN_APPROVE_APPLICATION_FAILURE = 'ADMIN_APPROVE_APPLICATION_FAILURE';

export const ADMIN_DECLINE_APPLICATION_REQUEST = 'ADMIN_DECLINE_APPLICATION_REQUEST';
export const ADMIN_DECLINE_APPLICATION_SUCCESS = 'ADMIN_DECLINE_APPLICATION_SUCCESS';
export const ADMIN_DECLINE_APPLICATION_FAILURE = 'ADMIN_DECLINE_APPLICATION_FAILURE';

export const CHAT_SEND_MESSAGE_REQUEST = 'CHAT_SEND_MESSAGE_REQUEST';
export const CHAT_SEND_MESSAGE_SUCCESS = 'CHAT_SEND_MESSAGE_SUCCESS';
export const CHAT_SEND_MESSAGE_FAILURE = 'CHAT_SEND_MESSAGE_FAILURE';
